# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-16 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='topic',
            new_name='title',
        ),
    ]
